services:
  backend:
    build:
      context: ./backend
    container_name: thinkboard-backend
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      PORT: 5001
    ports:
      - "5001:5001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: thinkboard-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
  db:
    image: mongo:latest
    container_name: thinkboard-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
volumes:
  mongo-data: 
  network:
    driver: bridge